'use client'

import Navbar from './components/Navbar'
import '../globals.css'
import { Inter } from 'next/font/google'
import { useAuthContext } from "@/context/AuthContext";
import { useRouter } from 'next/navigation';
import { useEffect } from 'react';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const { user } = useAuthContext()
  const { push } = useRouter();

  if (!user)  push('/signin');
 
  if (!user){
    return (
      <div>
        denegado
      </div>
    )
  }
  
  return (
    <div>
      <Navbar />
      <main className='container mx-auto p-2'>
        {children}
      </main>
    </div>
  )
}
